### ISSUE TITLE
raspbian baud rates not fully defined

### ISSUE THREAD

**Issue by markprocess** [euantorano/serialport.nim#12]
Trying nim c -r examples/writer.nim on raspbian stretch lite/pi3b+
```
    /home/pi/github.com/euantorano/serial.nim/src/serial/private/serialport/
    serialport_posix.nim(242, 12) Error: undeclared identifier: 'B57600'
```
I'm not familiar with how to approach this. I particularly need 115200 since that is the power-on baud rate.

Thanks, Mark

**Comment by euantorano** [comment]
Hi,

Can you please try using the `devel` verison of Nim rather than the `0.18.0` release? The new baud rates were added by @Jeff-Ciesielski to the Nim stdlib here: https://github.com/nim-lang/Nim/commit/f8723cd1e36ec939cc8e0e5bd4f181ff9ec5e99a

**Comment by WoodyAtHome** [comment]
Because this module does'nt compile with my ubuntu nim version I just downloaded and compiled the current git version of nim and nimble two hours ago.
I get the following error: 
`
/home/bert/.nimble/pkgs/serial-1.1.2/serial/serialstream.nim(117, 17) Error: type mismatch: got <proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe, locks: <unknown>.}> but expected 'proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.}'
`
Please help. I'm an absolute beginner and want to get into nim with learning by doing. But, sorry, this problem it to hard for me.
Alternatively I would be helpful if somebody can give me a nim-compiler version that runs with the current serial module.

Shouldn't the dependency section in the serial.nimble file be updated?

Thanks!!!!
